### ISSUE TITLE
Include guidance from notion

### ISSUE THREAD

**Issue by Burhan-Q** [DS3Lab/dataperf-vision-debugging#7]
This section from the `notion` [benchmark documentation](https://www.notion.so/xzyaoi/DataPerf-Data-Cleaning-Challenge-23b7296eb8fb46aea5c396120a978ed3) was not obvious anywhere else (GitHub readme, MLPref page, etc.).

> - Write an algorithmic approach in the `app/baselines/debugging.py` . It will be run and evaluate together with other baseline approaches.

This was important (at least for me) to understand how to incorporate with the evaluation code and was the only location (after a lot of looking around) I found this statement. I suspect it could be helpful to others as well to include with the GitHub readme and/or the [competition page](https://sites.google.com/mlcommons.org/dataperf/home_1/training-set-cleaning-vision/cleaning-overview).

**Comment by xzyaoi** [comment]
@Burhan-Q Thanks for the feedback, it will be updated soon! Sorry for the trouble.

Best regards,
Xiaozhe
