### ISSUE TITLE
Eval timing

### ISSUE THREAD

**Issue by Burhan-Q** [DS3Lab/dataperf-vision-debugging#8]
Since the online submission only requires the `.txt` files for evaluation, is it correct to presume that timing of the `CustomAppraiser` algorithm is not being evaluated? Does this mean the (alpha) assessment is solely based on `fraction_fixes` (count of proposed data to clean) and the `auc_score`?

**Comment by xzyaoi** [comment]
Hi @Burhan-Q, thanks for reaching out!

Yes, that's true. Right now in the current version, we only evaluate the fraction of fixes. We are working with Dynabench to allow participants to upload their algorithms in a `.py` file and we will then be able to evaluate the timing.

Best regards,
Xiaozhe

**Comment by Burhan-Q** [comment]
Thanks for the quick reply
